// src/lib/components/unityView.svelte
<script lang="ts">
    import unityStore from "$stores/unityStore";
    import { onMount } from "svelte";

    // state
    let unityCanvasEl = $state<HTMLCanvasElement>();


    // UNITY CONFIG
    const path = "/unity";
    const config = {
        dataUrl: path + "/data.gz",
        frameworkUrl: path + "/framework.js.gz",
        codeUrl: path + "/wasm.gz",
        streamingAssetsUrl: "StreamingAssets",
        companyName: "DefaultCompany",
        productName: "Kkumi-Land_unity",
        productVersion: "0.1",
    }


    /**
     * 유니티 로드 완료 시 실행될 함수
     */
    window.onUnityLoaded = () => unityStore.updateUnityState(true);


    /**
     * onMount()
    */
    onMount(() => {
        const script = document.createElement("script");
        script.src = `${path}/loader.js`;

        script.onload = async () => {
            try {
                const instance = await createUnityInstance(unityCanvasEl!, config);
                unityStore.updateUnityInstance(instance);
                console.log("%c ----- unity instance load success -----", "color: #fff; background-color: #0ea500");

            } catch (error: any) {
                console.error("%c ----- unity instance load fail -----", "color: #fff; background-color: red");
            }
        }

        document.body.appendChild(script);
    });
</script>



<canvas id="unity-canvas" bind:this={unityCanvasEl} width="960" height="600"></canvas>



<style>
    #unity-canvas {
        width: 100%;
        height: 100%;
    }
</style>

// src/components/unityView.vue
<script setup lang="ts">
    import { onMounted, useTemplateRef } from "vue";
import { unityStore } from "../store/unityStore";


    // UNITY CANVAS ELEMENT
    const unityCanvas = useTemplateRef("unity-canvas");

    // UNITY PATH (유니티 빌드파일 위치)
    const unityPath = "unity/";

    // UNITY CONFIG
    const config = {
        dataUrl: unityPath + "data.gz",
        frameworkUrl: unityPath + "framework.js.gz",
        codeUrl: unityPath + "wasm.gz",
        streamingAssetsUrl: "StreamingAssets",
        companyName: "DefaultCompany",
        productName: "Kkumi-Land_unity",
        productVersion: "0.1",
    };


    /**
     * UNITY LOAD
     * @param src string 유니티 로딩을 위한 build.loader.js 위치
     */
    function loadUnity(src: string) {
        const script = document.createElement("script");
        script.src = src;

        script.onload = () => {
            createUnityInstance(
                unityCanvas.value as HTMLCanvasElement,
                config
            ).then((unityInstance) => {
                console.log("%c ----- unity instance load success -----", "color: #fff; background-color: #0ea500");
                window.unityInstance = unityInstance;
            }).catch((msg) => {
                console.error("%c ----- unity instance load fail -----", "color: #fff; background-color: red");
            });
        };

        document.body.appendChild(script);
    };


    /**
     * onUnityLoaded 초기화
     */
    window.onUnityLoaded = () => {
        unityStore.state = true;
    };


    onMounted(() => {
        loadUnity("/unity/loader.js");
    });
</script>




<template>
	<canvas id="unity-canvas" ref="unity-canvas" width="960" height="600"></canvas>
</template>





<style scoped>
    #unity-canvas {
        width: 100%;
        height: 100%;
        background: none !important;
    }
</style>
